"""Actualización del modelo UserSpecialization

Revision ID: 20ce5d6c611d
Revises: e1ac0c53cbf1
Create Date: 2023-08-02 14:24:45.778530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ce5d6c611d'
down_revision = 'e1ac0c53cbf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_specializations_specialization_area_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'specialization_areas', ['area_id'], ['id'])
        batch_op.drop_column('specialization_area_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialization_area_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_specializations_specialization_area_id_fkey', 'specialization_areas', ['specialization_area_id'], ['id'])
        batch_op.drop_column('area_id')

    # ### end Alembic commands ###
