"""Actualización del modelo user

Revision ID: 87845465bc65
Revises: 20ce5d6c611d
Create Date: 2023-08-02 14:27:04.723657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87845465bc65'
down_revision = '20ce5d6c611d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('specialization_area_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('user_specializations_area_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'specialization_areas', ['specialization_area_id'], ['id'])
        batch_op.drop_column('area_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('level_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['id_card'])
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('level_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('user_specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_specializations_area_id_fkey', 'specialization_areas', ['area_id'], ['id'])
        batch_op.drop_column('specialization_area_id')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
