"""remove_countries_table

Revision ID: d42a94e8e408
Revises: e0f6bf16786c
Create Date: 2023-08-07 23:55:28.120184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42a94e8e408'
down_revision = 'e0f6bf16786c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_constraint('courses_fk_country_id',
                           table_name='courses')
        op.drop_column('country_id', table_name="courses")
        op.drop_table('countries')
    except Exception as e:
        print(
            f"An error occurred while running d42a94e8e408 revision: {str(e)}")
    # ### end Alembic commands ###
