careers = [
    "ingenieria informatica",
    "ingenieria en informatica",
    "ciencias de la computacion",
    "carrera de telecomunicaciones",
    "ingenieria de sistemas - virtual",
    "ingenieria de sistemas",
    "ingenierias",
    "ingenieria en sistemas digitales y comunicaciones",
    "ingenieria en ciencias de la computacion",
    "pedagogia de las ciencias experimentales - informatica",
    "tecnicatura universitaria en programacion",
    "ingenieria matematica",
    "carrera de computacion",
    "ingenieria de telecomunicaciones",
    "ingenieria de datos e inteligencial artificial",
    "licenciatura en ciencias de la computacion",
    "carreras de ingenieria",
    "carreras de ingenierias",
    "ciencia da computacao",
    "ciencia da computacao, engenharia civil, engenharia mecanica",
    "computacion",
    "escuela de ingenieria de sistemas y computacion",
    "escuela de ingenieria informatica",
    "escuela ingenieria en sistemas",
    "ingenieria de sistemas",
    "ingenieria de sistemas e informatica",
    "ingenieria",
    "ingenieria de sistemas",
    "ingenieria de sistemas de computacion",
    "ingenieria de sistemas e informatica",
    "ingenieria de sistemas e informatica, ingenieria industrial, ingeniera empresarial",
    "ingenieria de sistemas y computacion",
    "ingenieria de software",
    "ingenieria en computacion",
    "ingenieria en computacion inteligente",
    "ingenieria en inteligencia artificial",
    "ingenieria en sistemas computacionales",
    "ingenieria en sistemas computacionales en hardware",
    "ingenieria en sistemas digitales y comunicaciones",
    "ingenieria en sistemas electronicos y telecomunicaciones",
    "licenciatura en ciberseguridad",
    "licenciatura en ciencia de datos",
    "licenciatura en informatica",
    "licenciatura en informatica y tecnicatura universitaria en programacion",
    "licenciatura en ingenieria de sistemas y computacion",
    "licenciatura en ingenieria en sistemas computacionales",
    "licenciatura en ingenieria en sistemas y computacion",
    "licenciatura en redes informaticas",
    "licenciatura en tecnologia e informatica",
    "web",
    "ingenieria, arquitectura, urbanismo y afines",
    "ingenieria, arquitectura, urbanismo y afines",
    "ingenieria de sistemas y computacion",
    "ing. en sistemas computacionales",
]