taxonomy = {
    "ingenieria en informatica": {
        "desarrollo de software": {
            "lenguajes de programacion": {
                "java",
                "python",
                "javascript",
                "c#",
                "c++",
                "ruby",
                "php",
                "swift",
                "kotlin",
                "typescript",
                "html/css",
            },
            "frameworks y bibliotecas": {
                "react.js",
                "angular",
                "vue.js",
                "node.js",
                "django",
                "spring boot",
                "express.js",
                "laravel",
                "ruby on rails",
                "asp.net",
                "unity",
                "flutter",
                "xamarin",
                "electron",
                "flask",
            },
            "patrones de diseno": {
                "singleton",
                "factory",
                "observer",
                "mvc",
                "mvvm",
                "decorator",
                "strategy",
            },
        },
        "seguridad informatica": {
            "ciberseguridad": {
                "criptografia",
                "firewalls",
                "pruebas de penetracion",
            },
            "seguridad de redes": {
                "seguridad movil",
                "seguridad de aplicaciones web",
                "seguridad de bases de datos",
            },
            "desarrollo de software seguro": {
                "sdlc seguro",
                "proteccion de la privacidad",
                "seguridad en la nube",
            },
        },
        "inteligencia artificial": {
            "machine learning": {
                "procesamiento del lenguaje natural",
                "vision por computadora",
                "algoritmos geneticos",
                "mineria de datos",
            },
            "inteligencia artificial etica": {
                "etica en la ia",
                "bias y equidad",
                "transparencia y responsabilidad",
            },
            "redes neuronales artificiales": {
                "perceptron",
                "redes neuronales convolucionales",
                "redes neuronales recurrentes",
                "redes neuronales",
            },
        },
        "redes y comunicaciones": {
            "redes de computadoras": {
                "protocolos de red",
                "enrutamiento",
                "conmutacion",
            },
            "redes inalambricas": {
                "wi-fi",
                "bluetooth",
                "iot",
            },
            "tcp/ip": {},
            "cableado estructurado": {},
        },
        "bases de datos": {
            "sistemas de gestion de bases de datos (dbms)": {
                "sql server",
                "oracle",
                "sqlite",
                "mysql",
                "postgresql",
            },
            "bases de datos nosql": {
                "cassandra",
                "redis",
                "firebase",
                "mongodb",
            },
        },
        "ingenieria de software": {
            "algoritmos y estructuras de datos",
            "diseno de software",
            "metodologias agiles",
            "control de versiones (git)",
        },
        "sistemas distribuidos": {
            "sistemas embebidos",
            "computacion en tiempo real",
        },
        "computacion en la nube": {
            "proveedores de nube": {
                "amazon web services (aws)",
                "azure",
                "google cloud platform",
                "cloud computing",
            },
            "servicios en la nube": {
                "virtualizacion",
                "docker",
                "kubernetes",
                "serverless",
            },
            "automatizacion y orquestacion": {
                "terraform",
                "ansible",
                "puppet",
                "chef",
            },
            "ci/cd (entrega continua e integracion continua)": {},
        },
        "arquitectura de software": {
            "microprocesadores",
            "perifericos",
        },
        "realidad virtual y aumentada": {
            "realidad virtual (rv)",
            "realidad aumentada (ra)",
        },
        "diseno de interfaces de usuario (ui/ux)": {
            "herramientas de diseno ui/ux",
        },
        "analisis de datos": {
            "ciencia de datos",
            "visualizacion de datos",
        },
        "computacion grafica": {
            "computacion 3d",
        },
        "robotica": {},
        "computacion movil": {
            "android",
            "ios",
        },
        "big data": {
            "almacenamiento y procesamiento de datos": {
                "hadoop",
                "spark",
                "nosql",
                "apache kafka",
                "apache spark",
            },
        },
        "gestion de proyectos de ti": {},
        "sistemas embebidos": {},
        "computacion cuantica": {
            "algoritmos cuanticos",
            "criptografia cuantica",
            "aprendizaje automatico cuantico",
            "simulacion cuantica",
            "recocido cuantico",
            "correccion de errores cuanticos",
            "sensado cuantico",
            "redes cuanticas",
            "internet cuantico",
        },
        "bioinformatica": {},
        "internet de las cosas (iot)": {},
        "ingenieria de rendimiento de software": {
            "pruebas de rendimiento",
        },
        "experiencia de usuario (ux)": {
            "diseno ui/ux",
        },
        "minería de datos": {},
        "programación concurrente": {},
        "desarrollo web": {
            "frontend",
            "backend",
            "full-stack",
        },
        "optimización de sistemas": {},
        "simulación y modelado": {},
        "ingeniería de software orientada a objetos": {},
        "realidad aumentada": {},
        "ingeniería inversa": {},
        "ingeniería del conocimiento": {},
        "computación bioinspirada": {},
        "computación en tiempo real": {},
        "visión por computadora": {},
        "computación evolutiva": {},
        "redes neuronales artificiales": {},
        "ingeniería de sistemas": {},
        "ingeniería de datos": {},
        "computación forense": {},
        "automatización de procesos": {},
        "desarrollo de videojuegos": {},
        "interacción persona-computadora": {},
        "ingeniería de calidad de software": {},
        "programación de sistemas": {},
        "ingeniería de ciberseguridad": {},
        "desarrollo de aplicaciones móviles": {},
        "gestión de la tecnología": {},
        "ingeniería de redes": {},
        "ingeniería de pruebas de software": {},
        "ingeniería de sistemas embebidos": {},
        "computación distribuida": {},
        "computación paralela": {},
        "ingeniería de software en tiempo real": {},
        "ingeniería de requisitos": {},
        "gestión de la información": {},
        "realidad mixta": {},
        "ingeniería de sistemas inteligentes": {},
        "arquitectura empresarial": {},
        "automatización de pruebas de software": {},
        "ingeniería de usabilidad": {},
        "ingeniería de sistemas de información": {},
        "ingeniería de sistemas de tiempo real": {},
        "ingeniería de sistemas de información geográfica": {},
        "ingeniería de sistemas en la nube": {},
        "ingeniería de sistemas orientada a servicios": {},
        "ingeniería de sistemas colaborativos": {},
        "ingeniería de sistemas de control": {},
        "ingeniería de sistemas de producción": {},
        "ingeniería de sistemas electrónicos": {},
        "ingeniería de sistemas de transporte": {},
        "ingeniería de sistemas de seguridad": {},
        "ingeniería de sistemas de comunicación": {},
        "ingeniería de sistemas de energía": {},
        "ingeniería de sistemas de salud": {},
        "ingeniería de sistemas de gestión": {},
        "ingeniería de sistemas de calidad": {},
        "ingeniería de sistemas de diseño de software": {},
        "ingeniería de sistemas de desarrollo de software": {},
        "ingeniería de sistemas de mantenimiento de software": {},
        "ingeniería de sistemas de seguridad de software": {},
        "ingeniería de sistemas de pruebas de software": {},
        "ingeniería de sistemas de gestión de configuración de software": {},
        "ingeniería de sistemas de gestión de requisitos de software": {},
        "ingeniería de sistemas de desarrollo web": {},
        "ingeniería de sistemas de diseño de interfaces de usuario": {},
        "ingeniería de sistemas de desarrollo de aplicaciones móviles": {},
        "ingeniería de sistemas de análisis de seguridad": {},
        "ingeniería de sistemas de auditoría de seguridad": {},
        "ingeniería de sistemas de gestión de riesgos de seguridad": {},
        "ingeniería de sistemas de criptografía y seguridad de la información": {},
        "ingeniería de sistemas de protección de datos": {},
        "ingeniería de sistemas de seguridad en redes": {},
        "ingeniería de sistemas de administración de bases de datos": {},
        "ingeniería de sistemas de diseño de bases de datos": {},
        "ingeniería de sistemas de optimización de bases de datos": {},
        "ingeniería de sistemas de minería de datos": {},
        "ingeniería de sistemas de gestión de datos": {},
        "ingeniería de sistemas de visualización de datos": {},
        "ingeniería de sistemas de administración de proyectos": {},
        "ingeniería de sistemas de liderazgo y gestión": {},
    },
}